import React from 'react';

const HomeSection = () => {
    return (
        <div className='v-center-content'>
            <div class="intro">
              <h1>Oh hey there!</h1>
              <h2>I'm Kris, I design and develop websites</h2>
              <p>I do other things too of course. I like making music, brewing beer, baking bread and learning new things. </p>
              <p>I made this website to highlight my work experience and also use ut as an oppurtunity to develop with React</p>
            </div>
        </div>
    );
}

export default HomeSection;
